<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bluhmpresse"
 *
 * Auto generated by Extension Builder 2014-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bluhm Pressebereich',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Andreas Knoll',
	'author_email' => 'andreas.knoll@visia.de',
	'author_company' => 'Visia GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'vhs' => '1.8.4',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>